<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!-- 添加 WinForms 支持，仅仅为了拿一下屏幕宽度 -->
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>NPS_NotchPeninsula-logo.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

	<Version>1.3.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<!-- 新增的资源在这里引入 -->
    <Content Include="vcruntime140.dll" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="msvcp140.dll" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="NPS_NotchPeninsula-logo.ico" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\bilibili-logo.png" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\chrome-logo.png" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\edge-logo.png" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\potplayer-logo.jpg" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\qq-icon.png" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="data\image\wintoast-icon.png" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SkiaSharp" Version="2.88.8" />
		<PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.8" />
		<!-- 音频采集库 -->
		<PackageReference Include="NAudio.Core" Version="2.2.1" />
		<PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
	</ItemGroup>

</Project>